apiVersion: arubacloud.arubacloud.m.crossplane.io/v1alpha1
kind: Cloudserver
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/cloudserver
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    location: ITBG-Bergamo
    name: example-cloudserver
    network:
      elasticIpUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      securitygroupUriRefsRefs:
      - name: example
      subnetUriRefsRefs:
      - name: example
      vpcUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    settings:
      flavorName: CSO4A8
      keyPairUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    storage:
      bootVolumeUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    tags:
    - compute
    - example
    zone: ITBG-1
