apiVersion: arubacloud.m.crossplane.io/v1alpha1
kind: Containerregistry
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/containerregistry
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    billingPeriod: Hour
    location: ITBG-Bergamo
    name: example-container-registry
    network:
      publicIpUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      securityGroupUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      subnetUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      vpcUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    settings:
      adminUser: adminuser
      concurrentUsersFlavor: Small
    storage:
      blockStorageUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    tags:
    - container
    - test
