apiVersion: arubacloud.m.crossplane.io/v1alpha1
kind: Dbaasuser
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/dbaasuser
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    dbaasIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    passwordSecretRef:
      key: example-key
      name: example-secret
    username: example-user
