apiVersion: arubacloud.arubacloud.m.crossplane.io/v1alpha1
kind: Dbaas
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/dbaas
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    billingPeriod: Hour
    engineId: mysql-8.0
    flavor: DBO2A4
    location: ITBG-Bergamo
    name: basic-dbaas
    network:
      elasticIpUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      securityGroupUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      subnetUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      vpcUriRefSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storage:
      autoscaling:
        availableSpace: 100
        enabled: true
        stepSize: 10
      sizeGb: 100
    tags:
    - dbaas
    - test
    zone: ITBG-1
