apiVersion: arubacloud.m.crossplane.io/v1alpha1
kind: Keypair
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/keypair
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    location: ITBG-Bergamo
    name: example-keypair
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
    - compute
    - test
    valueSecretRef:
      key: example-key
      name: example-secret
