apiVersion: arubacloud.m.crossplane.io/v1alpha1
kind: Securityrule
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/securityrule
  labels:
    testing.upbound.io/example-name: http
  name: http
  namespace: crossplane-system
spec:
  forProvider:
    location: ITBG-Bergamo
    name: example-http-rule
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    properties:
      direction: Ingress
      port: "80"
      protocol: TCP
      target:
        kind: Ip
        value: 0.0.0.0/0
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
    - security
    - example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
