apiVersion: arubacloud.arubacloud.m.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    location: ITBG-Bergamo
    name: basic-vpc
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
    - network
    - test
