apiVersion: arubacloud.arubacloud.crossplane.io/v1alpha1
kind: Databasegrant
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/databasegrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    databaseSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dbaasIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    role: readwrite
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
