apiVersion: arubacloud.arubacloud.crossplane.io/v1alpha1
kind: Databasebackup
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/databasebackup
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    databaseSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    location: example-location
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
