apiVersion: arubacloud.crossplane.io/v1alpha1
kind: Securitygroup
metadata:
  annotations:
    meta.upbound.io/example-id: arubacloud/v1alpha1/securitygroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: ITBG-Bergamo
    name: example-security-group
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
    - security
    - example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
